# Preprocessing and image training
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipekit-ml01-
spec:
  entrypoint: pipekit-ml01
  templates:
  - name: pipekit-ml01
    steps:
    - - name: preprocess
        template: preprocess
      - name: train
        template: train
        arguments:
          artifacts:
          - name: message
            from: "{{steps.preprocess.outputs.artifacts.pipekit-ml01}}"

  - name: preprocess
    container:
      image: pipekit13/ml01-preprocess
    outputs:
      artifacts:
      - name: pipekit-ml01
        path: /tmp/
  - name: train
    inputs:
      artifacts:
      - name: pipekit-ml01
        path: /tmp/
    container:
      image: pipekit13/ml01-train
