# comment
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: pipekit-ml01-
spec:
  entrypoint: pipekit-ml01
  templates:
  - name: pipekit-ml01
    steps:
    - - name: preprocess
        template: preprocess
      - name: train
        template: train

  - name: preprocess
    container:
      image: pipekit13/ml01-preprocess
    outputs:
      artifacts:
      - name: ml01
        path: /tmp/
  - name: train
    inputs:
      artifacts:
      - name: ml01
        path: /tmp/
    container:
      image: pipekit13/ml01-train

