# Preprocessing and image training
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: ml-training
spec:
  entrypoint: ml-pipeline
  templates:
  - name: ml-pipeline
    steps:
    - - name: process
        template: preprocess
      - name: train
        template: train
        arguments:
          artifacts:
          - name: message
            from: "{{steps.process.outputs.artifacts.ml01}}"

  - name: preprocess
    container:
      image: pipekit13/ml01-preprocess
    outputs:
      artifacts:
      - name: ml01
        path: /tmp/
  - name: train
    inputs:
      artifacts:
      - name: ml01
        path: /tmp/
    container:
      image: pipekit13/ml01-train
